version: '3'

volumes:
    mongo_data: {}

services:
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: mongo
            ME_CONFIG_BASICAUTH_PASSWORD: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
        links:
            - mongo

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    pyramid:
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        command: /start-dev.sh
        depends_on:
            - mongo
        volumes:
            - .:/app
        ports:
            - "6543:6543"
        env_file: .env
